# Generated by Django 4.2.7 on 2026-01-14 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='atmosphere',
            field=models.JSONField(blank=True, default=list, help_text='Ortam: sessiz, müzikli, kalabalık, vs.'),
        ),
        migrations.AddField(
            model_name='visit',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('excellent', '😍 Bayıldım'), ('good', '🙂 İyi'), ('meh', '😐 Eh işte'), ('bad', '😕 Beğenmedim'), ('terrible', '🤮 Berbattı')], help_text='Genel izlenim', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='suitable_for',
            field=models.JSONField(blank=True, default=list, help_text='Kiminle gidilir: sevgili, arkadaş, aile, vs.'),
        ),
        migrations.AddField(
            model_name='visit',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Mekan tipi: butik, modern, mahalle, vs.'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='mood_tags',
            field=models.JSONField(blank=True, default=list, help_text='Eski mood tags (deprecated)'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='rating',
            field=models.IntegerField(blank=True, help_text='1-5 arası puan (opsiyonel)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visited_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='with_whom',
            field=models.CharField(blank=True, choices=[('sevgili', 'Sevgiliyle'), ('aile', 'Aileyle'), ('dost', 'Arkadaşlarla'), ('tek', 'Tek başıma'), ('is', 'İş')], max_length=20, null=True),
        ),
    ]
