# Generated by Django 4.2.7 on 2026-01-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('categories', models.JSONField(default=list, help_text="Örn: ['sevgili', 'aile', 'dost']")),
                ('tags', models.JSONField(default=list, help_text="Örn: ['samimi', 'sessiz', 'butik']")),
                ('price_level', models.CharField(choices=[('₺', '₺ - Ucuz'), ('₺₺', '₺₺ - Orta'), ('₺₺₺', '₺₺₺ - Pahalı')], default='₺₺', max_length=3)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
