# Generated by Django 4.2.7 on 2026-01-14 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='featured_features',
            field=models.JSONField(default=list, help_text="Öne çıkan özellikler: ['canlı müzik', 'vegan seçenek']"),
        ),
        migrations.AddField(
            model_name='place',
            name='hours',
            field=models.JSONField(blank=True, default=dict, help_text="Çalışma saatleri: {'monday': '09:00-22:00'}"),
        ),
        migrations.AddField(
            model_name='place',
            name='menu_link',
            field=models.URLField(blank=True, help_text='Menü linki (opsiyonel)', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='photos',
            field=models.JSONField(default=list, help_text="Fotoğraf URL'leri listesi"),
        ),
        migrations.AddField(
            model_name='place',
            name='short_description',
            field=models.CharField(blank=True, help_text='Kısa açıklama (vitrin kartı için)', max_length=300),
        ),
        migrations.AlterField(
            model_name='place',
            name='categories',
            field=models.JSONField(default=list, help_text="Örn: ['kafe', 'restoran', 'bar']"),
        ),
        migrations.CreateModel(
            name='PlacePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('like', 'Beğendim'), ('dislike', 'Beğenmedim'), ('save', 'Kaydet / Favori')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='places_plac_user_id_633e06_idx')],
                'unique_together': {('user', 'place')},
            },
        ),
    ]
