# Generated by Django 4.2.7 on 2026-01-15 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_featured_features_place_hours_place_menu_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='atmosphere_profile',
            field=models.JSONField(blank=True, default=dict, help_text="Atmosfer detayları: {'noise_level': 'düşük', 'lighting': 'soft', 'vibe': 'chill'}"),
        ),
        migrations.AddField(
            model_name='place',
            name='best_time_to_visit',
            field=models.CharField(blank=True, help_text="En iyi ziyaret zamanı: 'Hafta içi 17:00-20:00'", max_length=200),
        ),
        migrations.AddField(
            model_name='place',
            name='local_guide_note',
            field=models.TextField(blank=True, help_text='Local guide notu'),
        ),
        migrations.AddField(
            model_name='place',
            name='menu_highlights',
            field=models.JSONField(blank=True, default=list, help_text="Menü öne çıkanları: [{'name': 'Flat White', 'rating': 'iyi', 'emoji': '☕'}]"),
        ),
        migrations.AddField(
            model_name='place',
            name='one_line_summary',
            field=models.CharField(blank=True, help_text="Bir cümlelik özet: 'Sessiz çalışayım, iki kahve içeyim' mekanı", max_length=300),
        ),
        migrations.AddField(
            model_name='place',
            name='owner_description',
            field=models.TextField(blank=True, help_text='Dükkan sahibinin açıklaması'),
        ),
        migrations.AddField(
            model_name='place',
            name='peak_hours',
            field=models.JSONField(blank=True, default=dict, help_text="Yoğun saatler: {'start': '13:00', 'end': '18:00'}"),
        ),
        migrations.AddField(
            model_name='place',
            name='popular_orders',
            field=models.JSONField(blank=True, default=list, help_text="En çok sipariş edilenler: [{'item': 'Latte', 'percentage': 42}]"),
        ),
        migrations.AddField(
            model_name='place',
            name='power_outlets',
            field=models.CharField(blank=True, help_text="Priz durumu: 'bazı masalarda', 'her masada', 'yok'", max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='price_range',
            field=models.JSONField(blank=True, default=dict, help_text="Fiyat aralığı: {'min': 110, 'max': 190, 'currency': '₺'}"),
        ),
        migrations.AddField(
            model_name='place',
            name='similar_places',
            field=models.JSONField(blank=True, default=list, help_text="Benzer mekanlar: ['Soho House', 'Petra', 'Montag']"),
        ),
        migrations.AddField(
            model_name='place',
            name='target_audience',
            field=models.JSONField(blank=True, default=list, help_text="Hedef kitle: ['sessiz ortam + kahve + sohbet', 'estetik arayanlar', 'laptop çalışanlar']"),
        ),
        migrations.AddField(
            model_name='place',
            name='use_cases',
            field=models.JSONField(blank=True, default=dict, help_text="Kullanım senaryoları: {'date': True, 'friends': True, 'work': True, 'group': False, 'family': False}"),
        ),
        migrations.AddField(
            model_name='place',
            name='vibe_tags',
            field=models.JSONField(blank=True, default=list, help_text="Vibe etiketleri: ['Chill', 'Third-wave coffee', 'Local']"),
        ),
        migrations.AddField(
            model_name='place',
            name='wifi_quality',
            field=models.CharField(blank=True, help_text="Wi-Fi kalitesi: 'var', 'güçlü', 'yok'", max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='working_suitability',
            field=models.IntegerField(default=0, help_text='Çalışma uygunluğu % (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
