# Generated by Django 4.2.7 on 2026-01-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_atmosphere_profile_place_best_time_to_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='atmosphere_profile',
            field=models.JSONField(blank=True, default=dict, help_text="Atmosfer detayları: {'noise_level': 'düşük', 'lighting': 'soft', 'vibe': 'chill', 'mode': ['chill', 'creative work'], 'table_size': 'geniş'}"),
        ),
    ]
