# Generated by Django 4.2.7 on 2026-01-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_atmosphere_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='behavior_stats',
            field=models.JSONField(blank=True, default=dict, help_text="Davranış istatistikleri: {'average_stay_minutes': 87, 'laptop_ratio': 63, 'quietness_level': 'düşük gürültü'}"),
        ),
    ]
