# Generated by Django 4.2.7 on 2026-01-15 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0005_place_behavior_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('view', 'Görüntüleme'), ('swipe_like', 'Beğenme'), ('swipe_dislike', 'Beğenmeme'), ('swipe_save', 'Kaydetme'), ('detail_view', 'Detay Görüntüleme'), ('visit', 'Ziyaret'), ('review', 'Yorum')], max_length=20)),
                ('context', models.JSONField(blank=True, default=dict, help_text="Bağlam: {'time_of_day': '17:00', 'day_of_week': 'monday', 'device': 'mobile'}")),
                ('filters_used', models.JSONField(blank=True, default=list, help_text="Kullanılan filtreler: ['category:kafe', 'price:$$']")),
                ('session_id', models.CharField(blank=True, help_text='Oturum ID', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action_type'], name='places_user_user_id_d7d0f3_idx'), models.Index(fields=['place', 'action_type'], name='places_user_place_i_453823_idx'), models.Index(fields=['timestamp'], name='places_user_timesta_dbcfdb_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_likes', models.IntegerField(default=0, help_text='Kaç arkadaş beğendi')),
                ('friend_visits', models.IntegerField(default=0, help_text='Kaç arkadaş ziyaret etti')),
                ('friend_reviews', models.IntegerField(default=0, help_text='Kaç arkadaş yorum yaptı')),
                ('match_score', models.FloatField(default=0.0, help_text='Sosyal eşleşme skoru (0-1)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_matches', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('user', 'place')},
            },
        ),
        migrations.CreateModel(
            name='PlaceGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('similar', 'Benzer'), ('nearby', 'Yakın'), ('same_category', 'Aynı Kategori'), ('same_atmosphere', 'Aynı Atmosfer'), ('user_co_visit', 'Birlikte Ziyaret Edilen'), ('user_co_like', 'Birlikte Beğenilen')], max_length=20)),
                ('strength', models.FloatField(default=0.5, help_text='İlişki gücü (0-1)')),
                ('co_visit_count', models.IntegerField(default=0, help_text='Birlikte ziyaret sayısı')),
                ('co_like_count', models.IntegerField(default=0, help_text='Birlikte beğenilme sayısı')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='places.place')),
                ('to_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='places.place')),
            ],
            options={
                'ordering': ['-strength'],
                'unique_together': {('from_place', 'to_place', 'relationship_type')},
            },
        ),
    ]
