# Generated by Django 4.2.7 on 2026-01-14 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTasteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_weights', models.JSONField(default=dict, help_text="Kategori ağırlıkları: {'kafe': 0.35, 'brunch': 0.25}")),
                ('atmosphere_weights', models.JSONField(default=dict, help_text="Atmosfer ağırlıkları: {'estetik': 0.40, 'manzaralı': 0.20}")),
                ('context_weights', models.JSONField(default=dict, help_text="Context ağırlıkları: {'arkadaş': 0.60, 'sevgili': 0.25}")),
                ('style_label', models.CharField(blank=True, help_text="Örn: 'Brunch + Kahve + Estetik'", max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taste_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
