# Generated by Django 4.2.7 on 2026-01-20 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0006_userbehavior_socialmatching_placegraph'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Plan başlığı: 'Cumartesi Brunch'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Plan açıklaması')),
                ('planned_date', models.DateTimeField(blank=True, help_text='Planlanan tarih ve saat', null=True)),
                ('deadline', models.DateTimeField(blank=True, help_text='Oylama bitiş tarihi', null=True)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('voting', 'Oylama Aşamasında'), ('finalized', 'Kesinleşti'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20)),
                ('calendar_event_id', models.CharField(blank=True, help_text='Google Calendar event ID', max_length=200)),
                ('ical_uid', models.CharField(blank=True, help_text='iCal UID', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('selected_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_plans', to='places.place')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('yes', 'Evet'), ('maybe', 'Belki'), ('no', 'Hayır')], default='yes', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Oy notu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_votes', to='places.place')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='social.groupplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plan', 'place'], name='social_plan_plan_id_439758_idx')],
                'unique_together': {('plan', 'user', 'place')},
            },
        ),
        migrations.CreateModel(
            name='PlanPlaceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_note', models.TextField(blank=True, help_text='Neden bu mekan önerildi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_options', to='places.place')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_options', to='social.groupplan')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('plan', 'place')},
            },
        ),
        migrations.CreateModel(
            name='PlanParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_invited', models.BooleanField(default=True)),
                ('has_accepted', models.BooleanField(default=False)),
                ('has_declined', models.BooleanField(default=False)),
                ('notify_on_vote', models.BooleanField(default=True)),
                ('notify_on_finalize', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='social.groupplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invited_at'],
                'unique_together': {('plan', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='groupplan',
            index=models.Index(fields=['creator', 'status'], name='social_grou_creator_c4478c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupplan',
            index=models.Index(fields=['planned_date'], name='social_grou_planned_6807dc_idx'),
        ),
    ]
